# Generated by Django 4.1.6 on 2023-02-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author_alter_post_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=130),
        ),
    ]
